run:
  skip-files:
    - generated_.*\.go$
    - ".*_gen\\.go$"

linters:
  enable-all: true

  disable:
    - depguard
    - gci # 有効化したいけど vscode の保存時に勝手にフォーマットされ警告が出続けるので無効化
    - gofumpt
    - ireturn
    - revive
    - testpackage
    - varnamelen
    - wsl

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .JSON(
